### ISSUE TITLE
Small TODO Dump

### ISSUE THREAD

**Issue by rijkvp** [Rijk-van-Putten/MCQuest_Datapack#4]
- [x] Remove the 'nice music'
- [x] /team modify mod collisionRule never
- [x] /team modify mod nametagVisibility hideForOtherTeams
- [x] /team modify mod seeFriendlyInvisibles true
- [x] Call setup automatically when server starts
